#! /usr/bin/env bash


echo "== put object"

set -e

if [ -z "$1"]; then
    echo "There need to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

#Check for filename
if [ -z "$2"]; then
    echo "There need to be a bfilename prefix"
    exit 1
fi



BUCKET_NAME=$1
FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY \
--output text \


