#! /usr/bin/env bash

echo "== sync"
set -e

if [ -z "$1"]; then
    echo "There need to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

#Check for filename
if [ -z "$2"]; then
    echo "There need to be a bfilename prefix"
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2


# where we will store these files


OUTPUT_DIR="/tmp/s3-bash-scripts" 

rm -rf $OUTPUT_DIR
mkdir -p $OUTPUT_DIR

# generate a random number to determine files to create

NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1;i<=$NUM_FILES;i++)); do
    #generate random filename
    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

    #Generate random data and write it to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files