
AWSTemplateFormatVersion: "2010-09-09"
Description: A simple s3 Bucket

Resources:
  S3Bucket:
  #FROM: https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-s3-bucket.html#aws-resource-s3-bucket--examples
    Type: 'AWS::S3::Bucket'
    #We don't need to supply bucket name, AWS generates random name
    
      